name: Node.js CI

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          
      - name: 📥 Download deps
        uses: u0reo/npm-install@fix/restore-failure
          with:
            useRollingCache: true
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
