name: Node.js CI

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Debugging: List contents of the models directory
        run: ls -la ./models/

      - name: Debugging: Print working directory
        run: pwd

      - name: Debugging: List all environment variables
        run: printenv

      - name: Run tests
        run: npm test
